[git_metrics]
disabled = false

[shell]
disabled = false

[python]
detect_files = [
    "Pipfile",
    "__init__.py",
    "pyproject.toml",
    "requirements.txt",
    "setup.py",
    "tox.ini",
]

# [battery]
# full_symbol = "â€¢ "
# charging_symbol = "â‡¡ "
# discharging_symbol = "â‡£ "
# unknown_symbol = "â“ "
# empty_symbol = "â— "

[erlang]
symbol = "â“” "

[nodejs]
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š "
